#! /usr/bin/env bash
#
# Execute a test program built with the Testo library.
#
# The name of this script can be whatever you like. Popular names
# include 'test' and 'testo'.
#

here=$(dirname "${BASH_SOURCE[0]}")

# Run the compiled test program with the original arguments.
# The working directory is the one containing this script.
dune exec tests/test.exe --no-build --no-print-directory -- \
  "$@" --chdir "$here"
